# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Teddy
tagline:             'says hi'
description:         'brand new'
url:                 http://TeddyCho.github.io
baseurl:             'http://TeddyCho.github.io'
githubrepo:         'https://github.com/TeddyCho/TeddyCho.github.io/'
paginate:            5

# About/contact
author:
  name:              Teddy Cho
  url:               http://TeddyCho.github.io
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
